export const routes = {
  home: '/',
  login: '/login',
  groups: '/groups',
  join: '/join',
  profile: '/profile',
  groupDashboard: (groupId: string) => `/groups/${groupId}/dashboard`,
  groupPending: (groupId: string) => `/groups/${groupId}/pending`,
  groupAdminTasks: (groupId: string) => `/groups/${groupId}/admin-tasks`,
  groupOwners: (groupId: string) => `/groups/${groupId}/settings/owners`,
  groupRecurring: (groupId: string) => `/groups/${groupId}/settings/recurring`,
  groupPlayers: (groupId: string) => `/groups/${groupId}/players`,
  groupPlayer: (groupId: string, playerId: string) => `/groups/${groupId}/players/${playerId}`,
  groupPlayerStats: (groupId: string, playerId: string) => `/groups/${groupId}/players/${playerId}/stats`,
  groupPlayerEditCard: (groupId: string, playerId: string) => `/groups/${groupId}/players/${playerId}/edit-card`,
  groupEventNew: (groupId: string) => `/groups/${groupId}/events/new`,
  groupEvent: (groupId: string, eventId: string) => `/groups/${groupId}/events/${eventId}`,
  groupEventMvpVote: (groupId: string, eventId: string) =>
    `/groups/${groupId}/events/${eventId}?votar-mvp=${eventId}`,
  groupEventCheckIn: (groupId: string, eventId: string) => `/groups/${groupId}/events/${eventId}/check-in`,
  groupEventDraw: (groupId: string, eventId: string) => `/groups/${groupId}/events/${eventId}/draw`,
  groupEventTeams: (groupId: string, eventId: string) => `/groups/${groupId}/events/${eventId}/teams`,
  groupEventResult: (groupId: string, eventId: string) => `/groups/${groupId}/events/${eventId}/result`,
  groupEventEdit: (groupId: string, eventId: string) => `/groups/${groupId}/events/${eventId}/edit`,
} as const;
